### ISSUE TITLE
静态组件的使用问题

### ISSUE THREAD

**Issue by jy1989** [afeiship/react-inline-edit#1]
你好
根据 https://tencent.github.io/wepy/document.html#/?id=%E6%99%AE%E9%80%9A%E7%BB%84%E4%BB%B6%E5%BC%95%E7%94%A8
所说
现在Col或者Row组件如果要使用props，每一个不同props的组件都要新建一个实例，比如现在想用span将col 6:4开

```
<Row class="desc">
      <Col60>aaaaaa</Col60>
      <Col40>
        <view  >bbbbb</view>
      </Col40>
    </Row>
    <Row class="location">
      <Col60 span="60">bbbbbbb</Col60>
      <Col40 span="40">
        <view  >cccc</view>
      </Col40>
</Row>
```

```
components = {
    Col60: Col,
    Col40: Col
  };

```

只能够这样使用，但好像不太科学？ 请问有更好的方法引用么？

**Comment by afeiship** [comment]
记得这个是之前为wepy写的，后面发现`那个阶段`的 `wepy` 框架 `bug` 有点多，后面没有继续关注这个框架了。
如果需要使用 `grid`, 可以使用这套 `sass`， 这个我在项目中有长期使用，并会持续维护：

## 微信小程版
https://github.com/afeiship/weapp-sass-flexbox-grid

## web版：
https://github.com/afeiship/webkit-sass-flexbox-grid

**Comment by jy1989** [comment]
@afeiship 好的，感谢回复
